# Internal role variables and values that must NOT be overridden by the user.
#
# Variables defined here usually override earlier definitions due to the high
# precedence of this file. Each variable should have a concise comment above
# it, describing its purpose and how it fits into the role's functionality.

---

# List of facts used by the role (gathered on a best-effort basis if needed).
#
# To identify which subset a fact belongs to during development, you can use
# the following snippet:
#
# - ansible.builtin.setup:
#     gather_subset:
#       - '!min'
#       - '<subset_name, see parameter doc for details>'
__server_zabbix_used_facts:
  # from subset "distribution"
  - "distribution"
  - "distribution_major_version"
  - "distribution_version"
  - "distribution_release"
  - "os_family"


# List of platforms this role supports and was designed for.
#
# A warning will be issued if the list contains values and the role is executed
# on an unknown (not listed) platform, but execution will continue. Example:
#
# - name: "Fedora" # A ansible_facts value ('distribution' or 'os_family')
#   versions: # A ansible_facts value ('distribution_major_version' or
#     - "all" # 'distribution_version') or "all"
# - name: "Ubuntu"
#   versions:
#     - "22.04"
#     - "24.04"
# - name: "RedHat"
#   versions:
#     - "all"
# - name: "Debian"
#   versions:
#     - "all"
__server_zabbix_supported_platforms:
  - {name: "Debian",    versions: ["11", "12", "13"]}
  - {name: "Ubuntu",    versions: ["22.04", "24.04"]}
  - {name: "RedHat",    versions: ["all"]}
  - {name: "AlmaLinux", versions: ["all"]}
  - {name: "CentOS",    versions: ["all"]}
  - {name: "Fedora",    versions: ["all"]}


# List of package names to be installed when server_zabbix_state is
# set to "present". Resolves to zabbix-server-mysql or zabbix-server-pgsql
# depending on server_zabbix_db_type.
__server_zabbix_packages_install:
  - "zabbix-server-{{ server_zabbix_db_type }}"


# List of package names to be uninstalled when server_zabbix_state is
# set to "absent". This variable is useful when __server_zabbix_packages_install
# contains packages that are required for the managed software to function but
# should not be removed during uninstallation, as doing so could break other
# software. This is usually the case if there are common dependencies like
# "curl" or "openssl" which typically should remain installed even after
# uninstalling the software managed by this role.
__server_zabbix_packages_uninstall: "{{ __server_zabbix_packages_install }}"


# List of package names to be removed unconditionally before installation
# (e.g., to prevent conflicts or resolve incompatibilities).
__server_zabbix_packages_removal: []


# Service name for zabbix-server.
__server_zabbix_service_name: "zabbix-server"


# Path to the main configuration file.
__server_zabbix_config_path: "/etc/zabbix/zabbix_server.conf"


# Override defaults of dependencies used by this role (if any).

# nothing right now
