# Configuration: Manage settings, like adapting or creating config files.

---

- name: "Config | Default | Deploy zabbix_agent2.conf"
  ansible.builtin.template:
    src: "zabbix_agent2.conf.j2"
    dest: "{{ __agent2_zabbix_config_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart_agent2_zabbix"


- name: "Config | Default | Deploy PSK file"
  ansible.builtin.copy:
    content: "{{ agent2_zabbix_tls_psk_secret }}\n"
    dest: "{{ agent2_zabbix_tls_psk_file }}"
    owner: "zabbix"
    group: "zabbix"
    mode: "0400"
  when: agent2_zabbix_tls_psk_secret | length > 0
  no_log: true
  notify: "restart_agent2_zabbix"
